import Head from "next/head";
// import { api } from "~/utils/api";
import { Bot, Cog, Send } from "lucide-react";

export default function Home() {
  // const hello = api.example.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen w-full flex-col items-center justify-center gap-12 bg-gradient-to-br from-zinc-800 via-zinc-950 to-black p-4 text-white">
        <div className="flex max-w-2xl flex-col gap-2">
          <div className="flex items-center gap-6">
            <div className="rounded-full bg-gradient-to-br from-rose-400 via-fuchsia-500 to-indigo-500 p-4 text-white">
              <Bot />
            </div>
            <h1 className="rounded-r-full rounded-tl-full bg-zinc-800 px-6 py-4 shadow-lg">
              Hello!
            </h1>
          </div>
          <div className="flex items-center gap-6">
            <div className="invisible rounded-full bg-gradient-to-br from-rose-400 via-fuchsia-500 to-indigo-500 p-4 text-white">
              <Bot />
            </div>
            <h1 className="rounded-r-full rounded-bl-full bg-zinc-800 px-6 py-4 shadow-lg">
              I&apos;m LLaMA, an AI assistant developed by Meta AI that can
              understand and respond to human input in a conversational manner.
            </h1>
          </div>
        </div>
        <div className="flex flex-col items-center gap-4">
          <button className="flex items-center gap-2 rounded-xl bg-gradient-to-br from-pink-200 via-purple-300 to-indigo-300 px-6 py-3 font-semibold text-zinc-800 transition-transform duration-150 hover:scale-105">
            <span>Send a Message</span>
            <Send />
          </button>
          <button className="flex items-center gap-2 rounded-xl bg-gradient-to-r from-zinc-200 via-zinc-400 to-zinc-500 px-4 py-2 text-sm font-semibold text-zinc-800 transition-transform duration-150 hover:scale-105">
            <Cog />
            <span>Configure</span>
          </button>
        </div>
      </main>
    </>
  );
}
